### ISSUE TITLE
I cannot get lmutil and monitorlm to work

### ISSUE THREAD

**Issue by fastaemc** [rpi-dotcio/phpLicenseWatcher#136]
I followed the install instructions but where do I get the right files for lmutil and monitorlm from and where do I have to place them ? I use ubuntu 20.04
![image](https://user-images.githubusercontent.com/118543955/202726958-e749e5be-3752-4978-ab04-d1edb9227466.png)

**Comment by fastaemc** [comment]
I fixed the lmutil fail by copying the foles to /usr/local/nin/lmutil

But now still the monitorlm binary failess, where can I get that one from ?
![image](https://user-images.githubusercontent.com/118543955/202728649-2dc8b518-0d55-4ba0-9956-4d08f09c2cc2.png)

**Comment by pbailie** [comment]
1. monitorlm is provided by Mathematica.  If you do not license Mathematica, you should not need monitorlm and can ignore that fail warning.
   * We use both lmutil and monitorlm, so internal testing without monitorlm has been limited.  I intend to allow the system to continue working without monitorlm only.  Although when you have lmutil working, and still encounter problems related to monitorlm being absent, please file a bug report.
2. lmutil (and monitorlm) need to have execute permission for your server's www account.  In Ubuntu using Apache, this is typically `www-data`.
3. Please make sure `$lmutil_binary`, in `config.php` is set to lmutil's full path and file.
4. Points 2 and 3 are required for `license_util.php` to poll your server.

**Comment by fastaemc** [comment]
Hi Thanks for your response.
1.We want to use it to monitor matlab we don't use mathematica as far as I know.
2. The permissions seem to be in place
3. The path is also default and I placed the lmutil in the directory named in the config and gave the same permissions for the apache user

These are the steps I peformed:
mkdir /var/www/html/phplicensewatcher
chown -R www-data:www-data /var/www/html/phplicensewatcher
chmod 755 -R /var/www/html/phplicensewatcher  

mkdir /var/cache/phplw
chown -R www-data:www-data /var/cache/phplw
chmod 755 -R /var/cache/phplw

git clone https://github.com/rpi-dotcio/phpLicenseWatcher.git /var/www/html/phplicensewatcher

mysql

create database licenses;

mysql -f licenses < /var/www/html/phplicensewatcher/database/phplicensewatcher.sql


cp /var/www/html/phplicensewatcher/config/sample-config.php /var/www/html/phplicensewatcher/config/config.php
cp /var/www/html/phplicensewatcher/config/config.php /var/www/html/phplicensewatcher/config.php

create user 'phplw' identified by '***pw';
GRANT ALL PRIVILEGES ON licenses.* TO 'phplw'@'%';
ALTER USER 'phplw'@'localhost' IDENTIFIED WITH caching_sha2_password BY '***pw';
ALTER USER 'phplw'@'localhost' IDENTIFIED WITH mysql_native_password BY '***pw';

mkdir /usr/local/bin/monitorlm

mkdir /usr/local/bin/lmutil
cd /usr/local/bin/lmutil
wget https://www.plexim.com/sites/default/files/dstlm/flexnet_11_18_3_1_linux64.tar.gz
tar xvfz flexnet_11_18_3_1_linux64.tar.gz

I tried 
nano /etc/crontab  
and I tried:
crontab -e 
0 6 * * 1 php /var/www/html/phplicensewatcher/license_alert.php >> /dev/null
0,10,20,30,40,50 * * * * php /var/www/html/phplicencewatcher/license_util.php >> /dev/null
15 0 * * 1  php /var/www/html/phplicensewatcher/license_cache.php >> /dev/null

systemctl enable cron

**Comment by pbailie** [comment]
Looks like your steps did not give `www-data` executable permission for lmutil.  So either grant world execute permission, **OR** give file ownership to `www-data`, and grant user execute permission.

I see file permissions were set for the HTML directory and cache directory, but not the lmutil binary.

Hope that fixes it!

**Comment by pbailie** [comment]
I see the permissions set for lmutil at the end of your steps.  May I see the output for `$ ls -al /usr/local/bin/lmutil` ?

**Comment by pbailie** [comment]
Another check to make is make sure this line exists in config.php
```php
$lmutil_binary="/usr/local/bin/lmutil/lmutil";
```

**Comment by fastaemc** [comment]
Hi, thanks for your response here are the results of the checks:

root@rtdsys-t:/var/www/html/phplicensewatcher# ls -al /usr/local/bin/lmutil
total 5624
drwxr-xr-x 2 www-data www-data    4096 Nov 18 15:31 .
drwxr-xr-x 4 root     root        4096 Nov 18 16:15 ..
-rwxr-xr-x 1 www-data www-data 1694538 Nov 18 15:31 flexnet_11_18_3_1_linux64.tar.gz
-rwxr-xr-x 1 www-data www-data     793 Jan  3  2022 ._lmgrd
-rwxr-xr-x 1 www-data www-data 1286360 Jan  3  2022 lmgrd
-rwxr-xr-x 1 www-data www-data     793 Jan  3  2022 ._lmutil
-rwxr-xr-x 1 www-data www-data 1267992 Jan  3  2022 lmutil
-rwxr-xr-x 1 www-data www-data     701 Jan  3  2022 ._plexim
-rwxr-xr-x 1 www-data www-data 1481328 Jan  3  2022 plexim

And the config.php has this line:
$lmutil_binary="/usr/local/bin/lmutil";

**Comment by pbailie** [comment]
In your setup, I believe you need
```php
$lmutil_binary="/usr/local/bin/lmutil/lmutil";
```
That is "lmutil" is in the path twice because it is a directory off of `/usr/local/bin/`, but is also the name of the binary file.  You need to reference the full path *and* binary file.

**Comment by fastaemc** [comment]
Hi thank you again for your comment, I made the change restarted apache2, but still noting changes.

I also find it strange that it never tries to poll, couldn't it be a problem with the cronjob or anything?

![image](https://user-images.githubusercontent.com/118543955/204578347-f51efe7a-1b64-424b-b678-384c902beb58.png)

**Comment by pbailie** [comment]
I'm not a guru at crontabs, but your crontab looks syntactically OK to me.  If there is a problem with crontab, I suspect it will reside in the execution path of an entry (bad path or no execute permission for the crontab owner).

The polling is executed by `license_util.php`.  It requires that `$lmutil_binary` be set correctly, and that the `lmutil` binary file have execute permission to whoever is running the process.  When a webpage is requesting data (such as `license_alert` when accessed by the web), `lmutil` will be called by the apache user (typically `www-data`).  On the other hand, if this is a command-line execution (such as anything run by cron), then `lmutil` would be run by the owner of the crontab (as they are also running the script).  Also, any PHP script mentioned in the crontab needs read permission for the crontab owner.  (I say read permission this time because your crontab is directly calling the PHP runtime rather than directly calling the script).

**Comment by fastaemc** [comment]
I found one issue there was a typo in one of the cronjob tasks, but still, when I try to run it I get an access denied but all the rights seem to be correct:

root@rtdsys-t:/var/www/html/phplicensewatcher# php /var/www/html/phplicensewatcher/license_util.php
sh: 1: /usr/local/bin/lmutil: Permission denied
sh: 1: /usr/local/bin/lmutil: Permission denied
Error: Features table has no records.  Is the license server reachable?

/usr/local/bin/
drwxr-xr-x  2 www-data www-data 4096 Nov 18 15:31 lmutil

/usr/local/bin/lmutil
-rwxr-xr-x 1 www-data www-data 1694538 Nov 18 15:31 flexnet_11_18_3_1_linux64.tar.gz
-rwxr-xr-x 1 www-data www-data     793 Jan  3  2022 ._lmgrd
-rwxr-xr-x 1 www-data www-data 1286360 Jan  3  2022 lmgrd
-rwxr-xr-x 1 www-data www-data     793 Jan  3  2022 ._lmutil
-rwxr-xr-x 1 www-data www-data 1267992 Jan  3  2022 lmutil
-rwxr-xr-x 1 www-data www-data     701 Jan  3  2022 ._plexim
-rwxr-xr-x 1 www-data www-data 1481328 Jan  3  2022 plexim


and also the connection to the license server is open I can connect with it through telnet

**Comment by uChoh5fe** [comment]
`lmutil` should not be a directory, `lmutil` should be the executable...
```
cd /usr/local/bin
mv lmutil lmutil_11_18_3_1
ln -s lmutil_11_18_3_1/lmutil .
```
should work than (hopefully) ;-)

**Comment by uChoh5fe** [comment]
Have you seen this!

`grep lmutil_binary /var/www/html/phplicensewatcher/config.php`

says what?
> In your setup, I believe you need
> 
> ```
> $lmutil_binary="/usr/local/bin/lmutil/lmutil";
> ```
> 
> That is "lmutil" is in the path twice because it is a directory off of `/usr/local/bin/`, but is also the name of the binary file. You need to reference the full path _and_ binary file.

**Comment by fastaemc** [comment]
Hi yes I've seen that and tried then when I do that I get:

root@rtdsys-t:/var/www/html/phplicensewatcher# php /var/www/html/phplicensewatcher/license_util.php
sh: 1: /usr/local/bin/lmutil/lmutil: not found
sh: 1: /usr/local/bin/lmutil/lmutil: not found
Error: Features table has no records.  Is the license server reachable?

**Comment by uChoh5fe** [comment]
Can you execute:
`su www-data /usr/local/bin/lmutil/lmutil -V`

**Comment by fastaemc** [comment]
Hi yes it gives this:
su www-data /usr/local/bin/lmutil/lmutil -V
su from util-linux 2.34

**Comment by fastaemc** [comment]
No problem I'm glad you try to help.

This is what I get:

sudo -u www-data /usr/local/bin/lmutil/lmutil lmvinfo
sudo: unable to execute /usr/local/bin/lmutil/lmutil: No such file or directory

and these are the permissions:
ls -al /usr/local/bin/lmutil/lmutil
-rwxr-xr-x 1 www-data www-data 1267992 Jan  3  2022 /usr/local/bin/lmutil/lmutil

**Comment by uChoh5fe** [comment]
Ok...
can you execute `lmutil` when you `cd /usr/local/bin/lmutil/ && ./lmutil lmvinfo`
and what is with
`file /usr/local/bin/lmutil/lmutil`
`ldd /usr/local/bin/lmutil/lmutil`
`uname -a`

**Comment by fastaemc** [comment]
Hi I trid these options:
cd /usr/local/bin/lmutil/ && ./lmutil lmvinfo
bash: ./lmutil: No such file or directory

cd /usr/local/bin/lmutil/
&& ./lmutil lmvinfo
bash: syntax error near unexpected token `&&'

./lmutil lmvinfo
bash: ./lmutil: No such file or directory

file /usr/local/bin/lmutil/lmutil
/usr/local/bin/lmutil/lmutil: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-lsb-x86-64.so.3, for GNU/Linux 2.6.18, stripped

ldd /usr/local/bin/lmutil/lmutil
        linux-vdso.so.1 (0x00007fff231e7000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa7e5a6e000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa7e591f000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa7e5904000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa7e5712000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa7e570c000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa7e5702000)
        /lib64/ld-lsb-x86-64.so.3 => /lib64/ld-linux-x86-64.so.2 (0x00007fa7e5a9c000)

uname -a
Linux rtdsys-t 5.4.0-132-generic #148-Ubuntu SMP Mon Oct 17 16:02:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by uChoh5fe** [comment]
Ok, maybe I found a solution.

https://developer.arm.com/documentation/ka003732/latest

Please try
`ln -s  /lib64/ld-linux-x86-64.so.2 /lib64/ld-lsb-x86-64.so.3`

**Comment by fastaemc** [comment]
Yes that works !
Finally thank you very much :-) !

**Comment by pbailie** [comment]
@uChoh5fe Thank you for helping.
